apiVersion: apps/v1  # Specify the API version for the Deployment
kind: Deployment
metadata:
      name: DevSecOps-deployment
      spec: # Desired state for the Deployment
      replicas: 3 
      selector: # Label selector to identify the Pods managed by this Deployment
        matchLabels:
          app: DevSecOps-app #Immutable tags
      template: # how state should be
        metadata:
          labels:
            app: DevSecOps-app
        spec: # pod level config
          containers: # name/image of container
          - name: DevSecOps
            image: 450050505346.dkr.ecr.us-east-1.amazonaws.com/devsecops-testapp:latest # in production it is best practice to use a specific version tag instead of 'latest'. So rollouts are more predictable and controlled.
            ports:
            - containerPort: 80
