apiVersion: v1
kind: Service #service
metadata:
  name: devsecops-service
spec:
  type: Loadbalancer # creates AWS load balancer later
  selector: 
    app.kubernetes.io/name: devsecops-app # endpoint service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
